-- Create Database

CREATE DATABASE IF NOT EXISTS PHARMA_COMMERCIAL_ANALYTICS;

USE DATABASE PHARMA_COMMERCIAL_ANALYTICS;

-- Create Schemas

CREATE SCHEMA IF NOT EXISTS LANDING;

CREATE SCHEMA IF NOT EXISTS FOUNDATION;

CREATE SCHEMA IF NOT EXISTS CURATED;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE SCHEMA IF NOT EXISTS AUDIT;

-- Create Warehouses

CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
WITH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;